# Generated by Django 4.2.7 on 2026-02-24 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number (e.g. 0712345678 or 254712345678)', regex='^(?:\\+254|254|0)?([71]\\d{8})$')]),
        ),
    ]
