# Generated by Django 4.2.7 on 2026-02-25 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number (e.g. 0712345678 or 254712345678)', regex='^(?:\\+254|254|0)?([71]\\d{8})$')]),
        ),
    ]
