# Generated by Django 4.2.7 on 2026-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo image (recommended: 200x50px)', null=True, upload_to='site_settings/')),
                ('background', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='site_settings/')),
                ('site_name', models.CharField(default='TJ Naturals', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
