# Generated by Django 4.2.7 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_secondary',
            field=models.ImageField(blank=True, help_text='Second hero background image', null=True, upload_to='site_settings/'),
        ),
    ]
